version: '3'

services:
  web:
    container_name: QuadraticEquationsSolver
    build: .
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./project:/usr/src/app
    ports:
      - 8000:8000